
import { Container, TextContainer, Texto, Title} from "./styles";
import Header from "../../Components/Header/header";


export default function Questions (){
  const texts = [
    "Deus = Espírito Amor.",
    "Jesus Cristo = Sacrifício pelo",
    "Igual.",
    "Céus = Espíritos Humanos.",
    "Terra = Alma",
    "Águas = Energias.",
    "Luz = Informação = Dia/Sol = Informação para Informado.",
    "Trevas = Desinformação = Noite/Lua = Informação para desinformado.",
    "Firmamento = Mente.",
    "Vegetais e Animais da Terra = Sensações, Sentimentos da Alma.",
    "Homem = Consciência",
    "Mulher = Subconsciência.",
    "Jardim do Éden = Cérebro.",
    "Satanás = Diabo = Dragão = Ócio/Ignorância/Medo.",
    "Caim = Culpa",
    "Abel = Arrependimento",
    "Rio Pisom = energia Motor = Havilá.",
    "Rio Giom = energia Emocional = Cuxe.",
    "Rio Tigre = energia Verbal.",
    "Rio Eufrates = energia Sexual.",
    "Anjo = Inteligência",
    "Adão = Consciência na Alma.",
    "Sete = Postura.",
    "Enos = Clamor.",
    "Enoque = Consagração.",
    "Matusalém = Longanimidade.",
    "Noé = Justiça.",
    "Sem = Sensatez.",
    "Jafé = Respeito.",
    "Cam (Cão) = Insensatez.",
    "Canaã = Estupidez.",
    "Abrão = Bênção.",
    "Ismael = Misericórdia.",
    "Abraão = Perfeição.",
    "Isaque = Sacrifício.",
    "Jacó = Paciência.",
    "Israel = Obediência.",
    "Esaú = Destreza.",
    "Jerusalém = Fé.",
    "Sião = Vontade.",
    "Judá = Esperança.",
    "Salém = Paz.",
    "Melquisedeque = Consciência da Alma",
    "Rei = Energia Consciente.",
    "José = Prosperidade",
    "Davi = Energia Consciente da Obediência.",
    "Moisés = Liberdade.",
    "Josué = Entrega",
    "Elias = Honra",
    "João = Revelação",
    "Isabel = Dignidade",
    "Maria = Pureza",
    "Coração = Sabedoria.",
    "Alma = Consciência.",
    "Espírito = Essência.",
    "Fogo = Energia Concentrada.",
    "Assíria = Humildade/Orgulho.",
    "Egito = Adoração/Idolatria.",
    "Filistia = Gana/Avareza.",
    "Moabe = Ira (vileza)/Calma.",
    "Nínive = Insipiência",
    "Dumá = Ansiedade.",
    "Sodoma e Gomorra = Perversidade e Loucura.",
    "Tiro = Inveja.",
    "Sidom = Incredulidade.",
    "Sinear = Impiedade.",
    "Babilônia = Egoísmo.",
    "Gogue e Magogue = Estima e Estimação.",
    "Pérsia = Retidão.",
    "Grécia = Experiência.",
    "Roma = Hombridade.",
    "Livro = Conhecimento.",
    "Videira = Poder = Vinho = Sumo do Poder.",
    "Figueira = Redenção.",
    "Trigo = Filho de Deus.",
    "Fermento = Doutrina.",
    "Pomba = Simplicidade.",
    "Serpente = Prudência/Ignorância.",
    "Crocodilo (leviatã) = Coragem/Soberba.",
    "Águia = Segurança/Indiferença.",
    "Avestruz = Abnegação/Desinteresse.",
    "Gafanhoto = Suspeita.",
    "Escorpião = Intenção.",
    "Bode/Cabra = Independência/Indeterminação.",
    "Jumento/Asno = Desprendimento/Indomabilidade",
    "Cavalo = Força/Fúria.",
    "Touro = Interesse/Violência.",
    "Hipopótamo = Firmeza.",
    "Leão = Determinação.",
    "Cordeiro = Sacrifício pelo Igual.",
    "Peixe = Alegria.",
    "Sete Espíritos de Deus = Verbo, Eternidades, Universos, Galáxias, Estrelas, Planetas, Carnes.",
    "Sete Igrejas do Apocalipse = Éfeso/Médios, Esmirna/Pobres, Pérgamo/Ricos, Tiatira/Cientistas, Sardes/Almas, Filadélfia/Mulheres, Laodicéia/Jovens.",
    "Vinte e quatro Anciãos = Vinte e quatro Horas.",
    "Sete Chifres do Cordeiro = Informação Automática, Informação Mnemônica, Informação Racional, Informação Imaginativa, Informação Consciente, Informação Inteligente, Informação Espiritual.",
    "Primeiro Selo = Teocracia Cristã = Vinte e Sete Livros do Novo Testamento de Deus Pai, Filho e Espírito Santo.",
    "Segundo Selo = Belicocracia.",
    "Terceiro Selo = Bancocracia.",
    "Quarto Selo = Bancocracia + Belicocracia = Banco-Belicocracia.",
    "Quinto Selo = Sacerdócio Fiel.",
    "Sexto Selo = Tribunal.",
    "Sétimo Selo = Sete Trombetas.",
    "Primeira Trombeta = Pólvora.",
    "Segunda Trombeta = Bússola.",
    "Terceira Trombeta = Mercúrio.",
    "Quarta Trombeta = Imprensa.",
    "Quinta Trombeta = Petróleo.",
    "Sexta Trombeta = Eletricidade.",
    "Sete Trovões = Hipotálamo, Epífise, Hipófise, Timo, Tireóide, Supra-Renais, Gônadas.",
    "Duas Testemunhas = Política e Tecnologia.",
    "Sétima Trombeta = Julgamento.",
    "Mulher vestida de Sol e seu Filho Varão = Subconsciente Informado gerando o Consciente Espírito Amor.",
    "dragão de sete cabeças = Ignorância Intencional.",
    "Sete cabeças do dragão = Cobiça, Luxúria, Preguiça, Vaidade, Ira, Inveja e Soberba.",
    "Besta de Sete Cabeças = Capitalismo.",
    "Sete cabeças da besta = Sete Montes = Barbarismo, Feudalismo, Colonialismo, Absolutismo, Socialismo, NaziFascismo, Imperialismo.",
    "Sete cabeças = Sete Reis = energia consciente do apego à Visão, Audição, Tato, Paladar, Olfato (Cinco caídos), Emoção (Existe), Sexo (Chega e dura pouco).",
    "Cabeça ferida de morte e curada = Monte = Absolutismo.",
    "Cabeça ferida de morte e curada = Rei = energia consciente do apego à visão.",
    "Oitavo Rei = Capitalismo.",
    "Boca da Besta = Comunicações egoístas e orgulhosas.",
    "Dez Chifres = Indústrias Metalúrgica, Bélica, Hídrica, Alimentícia, Locomotiva, Energética, Química, Mineral, Madeireira, Têxtil.",
    "Besta de Dois Chifres = Revolução Industrial.",
    "Dois Chifres = Militarismo e Mercantilismo (Mercadismo).",
    "Imagem à Besta = Sistema Capitalista.",
    "Falso Profeta = Religiosismo.",
    "Reis da Terra = Principais Energias da Alma.",
    "Mulher Grande Meretriz Mãe das Prostitutas = Subconsciência Egoísta.",
    "Grande Cidade Babilônia = Egoísmo.",
    "Três Partes da Grande Cidade = Orgulho Egoísta, Sexo Egoísta, Fome Egoísta.",
    "Três Espíritos imundos de demônios = Três predisposições imundas da inteligência.",
    "Semelhantes a Anfíbios = semelhança de Sentimento que surge nas Energias (Águas) e buscam transferência para Alma (Terra).",
    "Da Boca da Ignorância/Dragão = Sexo Egoísta.",
    "Da Boca do Capitalismo/Besta = Orgulho Egoísta.",
    "Da Boca do Religiosismo/Falso Profeta = Fome Egoísta.",
    "Inferno = Frequência.",
    "Morte = Vibração",
    "Cavaleiro Fiel e Verdadeiro = Filho",
    "Varão da Mulher vestida de Sol = Forte Consciente Espírito Amor."
];

return ( 
    <Container>
        <Header></Header>
        <Title>INSTRUMENTO DE INSTRUÇÃO</Title>
        <TextContainer>
            {texts.map((line, index) => (
                <Texto key={index}>{line}</Texto>
            ))}
        </TextContainer>
    </Container>
)

    }